#
# Copyright (c) 2016 Marat Abrarov (abrarov@gmail.com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

os: Visual Studio 2015

build:
  verbosity: detailed

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

environment:
  matrix:
    - MSVC_VERSION: 14.0
      BOOST_VERSION: 1.59.0
      QT_VERSION: 5.6

matrix:
  fast_finish: true

install:
  - ps: >-
      switch ($env:PLATFORM) {
        "x86" {
          $env:VCVARS_PLATFORM="x86"
          $env:QT_DIR_SUFFIX=""
        }
        "x64" {
          $env:VCVARS_PLATFORM="amd64"
          $env:QT_DIR_SUFFIX="-x64"
        }
      }
  - ps: >-
      switch ($env:MSVC_VERSION) {
        "14.0" {
          $env:MSVS_HOME="%ProgramFiles(x86)%\Microsoft Visual Studio 14.0"
        }
        "12.0" {
          $env:MSVS_HOME="%ProgramFiles(x86)%\Microsoft Visual Studio 12.0"
        }
        "11.0" {
          $env:MSVS_HOME="%ProgramFiles(x86)%\Microsoft Visual Studio 11.0"
        }
        "10.0" {
          $env:MSVS_HOME="%ProgramFiles(x86)%\Microsoft Visual Studio 2010"
        }
        "9.0" {
          $env:MSVS_HOME="%ProgramFiles(x86)%\Microsoft Visual Studio 2008"
        }
      }

#  - set PATH=%PATH%;%QTDIR%\bin

before_build:
  - call "%MSVS_HOME%\VC\vcvarsall.bat" "%VCVARS_PLATFORM%"
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - mkdir build
#  - cd build
#  - cmake -D CMAKE_BUILD_TYPE=%CONFIGURATION% -D gtest_force_shared_crt=ON -G "%CMAKE_GENERATOR%" ..
#  - cmake --build . --config $BUILD_TYPE --clean-first
#  - ctest --build-config $BUILD_TYPE --verbose
