#
# Copyright (c) 2016 Marat Abrarov (abrarov@gmail.com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

os: Visual Studio 2015

build:
  verbosity: detailed

environment:
  matrix:
    - MSVC_VERSION: 14.0
      BOOST_VERSION: 1.59.0
      QT_VERSION: 5.6
      BUILD_CONFIGURATION: Release
    - MSVC_VERSION: 14.0
      BOOST_VERSION: 1.59.0
      QT_VERSION: 5.6
      BUILD_CONFIGURATION: Debug

install:
  - ps: |
      switch ($env:PLATFORM) {
        "x86" {
          $env:VCVARS_PLATFORM="x86"
          $env:QT_DIR_PLATFORM_SUFFIX=""
        }
        "x64" {
          $env:VCVARS_PLATFORM="amd64"
          $env:QT_DIR_PLATFORM_SUFFIX="-x64"
        }
      }
      switch ($env:MSVC_VERSION) {
        "14.0" {
          $env:MSVS_HOME="%ProgramFiles(x86)%\Microsoft Visual Studio 14.0"
          $env:QT_DIR_TOOLCHAIN_SUFFIX="msvc2015"
        }
        "12.0" {
          $env:MSVS_HOME="%ProgramFiles(x86)%\Microsoft Visual Studio 12.0"
          $env:QT_DIR_TOOLCHAIN_SUFFIX="msvc2013"
        }
        "11.0" {
          $env:MSVS_HOME="%ProgramFiles(x86)%\Microsoft Visual Studio 11.0"
          $env:QT_DIR_TOOLCHAIN_SUFFIX="msvc2012"
        }
        "10.0" {
          $env:MSVS_HOME="%ProgramFiles(x86)%\Microsoft Visual Studio 10.0"
          $env:QT_DIR_TOOLCHAIN_SUFFIX="msvc2010"
        }
        "9.0" {
          $env:MSVS_HOME="%ProgramFiles(x86)%\Microsoft Visual Studio 9.0"
          $env:QT_DIR_TOOLCHAIN_SUFFIX="msvc2008"
        }
      }
      switch ($env:BOOST_VERSION) {
        "1.59.0" {
          $env:BOOST_HOME="C:\Libraries\boost_1_59_0"
        }
        "1.58.0" {
          $env:BOOST_HOME="C:\Libraries\boost_1_58_0"
        }
        "1.56.0" {
          $env:BOOST_HOME="C:\Libraries\boost"
        }
      }
      switch ($env:QT_VERSION) {
        "5.6" {
          $env:QT_HOME="C:\Qt\5.6\$env:QT_DIR_TOOLCHAIN_SUFFIX$env:QT_DIR_PLATFORM_SUFFIX"
        }
        "5.5" {
          $env:QT_HOME="C:\Qt\5.5\$env:QT_DIR_TOOLCHAIN_SUFFIX$env:QT_DIR_PLATFORM_SUFFIX"
        }
        "5.4" {
          $env:QT_HOME="C:\Qt\5.4\$env:QT_DIR_TOOLCHAIN_SUFFIX$env:QT_DIR_PLATFORM_SUFFIX"
        }
        "5.3" {
          $env:QT_HOME="C:\Qt\5.3\$env:QT_DIR_TOOLCHAIN_SUFFIX$env:QT_DIR_PLATFORM_SUFFIX"
        }
      }

before_build:
  - cmd: echo MSVC_VERSION        %MSVC_VERSION%
  - cmd: echo BOOST_VERSION       %BOOST_VERSION%
  - cmd: echo QT_VERSION          %QT_VERSION%
  - cmd: echo BUILD_CONFIGURATION %BUILD_CONFIGURATION%
  - cmd: echo VCVARS_PLATFORM     %VCVARS_PLATFORM%
  - cmd: echo MSVS_HOME           %MSVS_HOME%
  - cmd: echo BOOST_HOME          %BOOST_HOME%
  - cmd: echo QT_HOME             %QT_HOME%
  - cmd: call "%MSVS_HOME%\VC\vcvarsall.bat" "%VCVARS_PLATFORM%"
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - mkdir build
  - cd build
#  - cmake -D CMAKE_BUILD_TYPE=%CONFIGURATION% -D gtest_force_shared_crt=ON -G "%CMAKE_GENERATOR%" ..
#  - cmake --build . --config $BUILD_TYPE --clean-first
#  - ctest --build-config $BUILD_TYPE --verbose

build_script:
  - cmd: cmake --version
