#
# Copyright (c) 2016 Marat Abrarov (abrarov@gmail.com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

language: cpp
sudo: false

matrix:
  include:
    - env: COMPILER=g++-5 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &gcc5
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-5
            - g++-5
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
            - boost-latest
            - ubuntu-sdk-team
    - env: COMPILER=g++-5 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *gcc5

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_CXX_COMPILER=$COMPILER -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D ma_force_qt5=ON ..
  - cmake --build . --config $BUILD_TYPE --clean-first
  - ctest --build-config $BUILD_TYPE --verbose
