#
# Copyright (c) 2016 Marat Abrarov (abrarov@gmail.com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

language: cpp
sudo: required
dist: trusty

env:
  global:
    - secure: "rxP3V/oY3YSGIaUkRjCK302ueka7zmxdEWBLnec4nW1We8ys0HS/WL//FkNyTQBHNILerfHCtKLMg4tX1ccxC9JPiS9biyDYDOMZQYlXv6UcJBoJBThcKUNcC8vxSrPc1rgSgbai+FvmwiXA/VmHPWInAhcUmsMqCocElR+lLf8gI9Y9VbiuEc3fOSq4KgeIdmblHfdA2BkCc96hR34gOa6r+C+gA0Y3eD3sQnAlzwYG0uXIaRcO0CPI2TJk0HJHc6Lzzpkvwd9vWNMlfRa7U2aKMtow44VPa9dQ+O2BI1H/+GT0eF+7wGPRZWYpkr9EKnzFJf+CFUnWz8BWULp5TsLUa6e6LCnkWiVfXeP/5+LNOrmYMZia6Ko0E9jY595y0aNKAPpzC535ecuYZ9PrV6W12ginutteKRgOjo0H1Rat7QkJ89FJiAXEmhQkiCu5D2FMsgRd6N6+3G06h4DEZeZ7wsUUZV3SpSSkl1wfQNUw0ddNDbTtOCw007md00LSTVPRaLVRuu7weyCKHqgY+h78yhvwAREKEK+qmnzcFBS6bwg5NReKYDiMK1JzgbiUPnqnvZ69rMEErfOWb4ET1FJ382dUtlGoUIbJIAY+1WlLRLTKkIBAeEnVWQFvDFPSYHeaLCxeNlacM76q9S5lBEY6XlC3g+nQidGnBLhGqZU="
    - COVERAGE_BUILD=OFF

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

matrix:
  include:
    # Default GCC, Boost 1.55. Qt 5.x. Used for Coverity scan.
    - env: C_COMPILER=gcc CXX_COMPILER=g++ BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE COVERAGE_BUILD=OFF
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: &gcc-package-sources
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - boost-latest
        coverity_scan:
          project:
            name: "mabrarov/asio_samples"
            description: "Build submitted via Travis CI"
          notification_email: abrarov@gmail.com
          build_command_prepend: "cd $TRAVIS_BUILD_DIR && rm -rf build && mkdir build && cd build && cmake -D CMAKE_C_COMPILER=$C_COMPILER -D CMAKE_CXX_COMPILER=$CXX_COMPILER -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D ma_force_qt_major_version=$QT_MAJOR_VERSION .."
          build_command: make
          branch_pattern: coverity_scan
    # Default GCC, Boost 1.55. Qt 5.x. Used for collecting information about test coverage.
    - env: C_COMPILER=gcc CXX_COMPILER=g++ BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG COVERAGE_BUILD=ON
      compiler: gcc
      addons:
        apt:
          packages:
            - lcov
            - cmake
            - cmake-data
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: *gcc-package-sources
    # GCC 5, Boost 1.55. Qt 5.x
    - env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc5-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-5
            - g++-5
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: *gcc-package-sources
    - env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc5-boost155-qt5
    # GCC 4.9, Boost 1.55. Qt 5.x
    - env: C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc49-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.9
            - g++-4.9
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: *gcc-package-sources
    - env: C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc49-boost155-qt5
    # GCC 4.8, Boost 1.55. Qt 5.x
    - env: C_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc48-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.8
            - g++-4.8
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: *gcc-package-sources
    - env: C_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc48-boost155-qt5
    # GCC 4.6, Boost 1.55. Qt 5.x
    - env: C_COMPILER=gcc-4.6 CXX_COMPILER=g++-4.6 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc46-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.6
            - g++-4.6
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: *gcc-package-sources
    - env: C_COMPILER=gcc-4.6 CXX_COMPILER=g++-4.6 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc46-boost155-qt5
    # Clang 3.6, Boost 1.55. Qt 5.x
    - env: C_COMPILER=clang-3.6 CXX_COMPILER=clang++-3.6 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
      compiler: clang
      addons: &addons-clang36-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - clang-3.6
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: &llvm36-package-sources
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - boost-latest
    - env: C_COMPILER=clang-3.6 CXX_COMPILER=clang++-3.6 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
      compiler: clang
      addons: *addons-clang36-boost155-qt5
    # Clang 3.7, Boost 1.55. Qt 5.x
    - env: C_COMPILER=clang-3.7 CXX_COMPILER=clang++-3.7 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
      compiler: clang
      addons: &addons-clang37-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - clang-3.7
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: &llvm37-package-sources
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - boost-latest
    - env: C_COMPILER=clang-3.7 CXX_COMPILER=clang++-3.7 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
      compiler: clang
      addons: *addons-clang37-boost155-qt5
    # Clang 3.8, Boost 1.55. Qt 5.x
    - env: C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=DEBUG
      compiler: clang
      addons: &addons-clang38-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - clang-3.8
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: &llvm38-package-sources
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - boost-latest
    - env: C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BOOST_VERSION=1.55 QT_MAJOR_VERSION=5 BUILD_TYPE=RELEASE
      compiler: clang
      addons: *addons-clang38-boost155-qt5
    # GCC 5, Boost 1.55. Qt 4.x
    - env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc5-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-5
            - g++-5
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *gcc-package-sources
    - env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc5-boost155-qt4
    # GCC 4.9, Boost 1.55. Qt 4.x
    - env: C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc49-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.9
            - g++-4.9
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *gcc-package-sources
    - env: C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc49-boost155-qt4
    # GCC 4.8, Boost 1.55. Qt 4.x
    - env: C_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc48-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.8
            - g++-4.8
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *gcc-package-sources
    - env: C_COMPILER=gcc-4.8 CXX_COMPILER=g++-4.8 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc48-boost155-qt4
    # GCC 4.6, Boost 1.55. Qt 4.x
    - env: C_COMPILER=gcc-4.6 CXX_COMPILER=g++-4.6 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc46-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.6
            - g++-4.6
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *gcc-package-sources
    - env: C_COMPILER=gcc-4.6 CXX_COMPILER=g++-4.6 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc46-boost155-qt4
    # Clang 3.6, Boost 1.55. Qt 4.x
    - env: C_COMPILER=clang-3.6 CXX_COMPILER=clang++-3.6 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=DEBUG
      compiler: clang
      addons: &addons-clang36-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - clang-3.6
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *llvm36-package-sources
    - env: C_COMPILER=clang-3.6 CXX_COMPILER=clang++-3.6 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=RELEASE
      compiler: clang
      addons: *addons-clang36-boost155-qt4
    # Clang 3.7, Boost 1.55. Qt 4.x
    - env: C_COMPILER=clang-3.7 CXX_COMPILER=clang++-3.7 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=DEBUG
      compiler: clang
      addons: &addons-clang37-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - clang-3.7
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *llvm37-package-sources
    - env: C_COMPILER=clang-3.7 CXX_COMPILER=clang++-3.7 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=RELEASE
      compiler: clang
      addons: *addons-clang37-boost155-qt4
    # Clang 3.8, Boost 1.55. Qt 4.x
    - env: C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=DEBUG
      compiler: clang
      addons: &addons-clang38-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - clang-3.8
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *llvm38-package-sources
    - env: C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 BOOST_VERSION=1.55 QT_MAJOR_VERSION=4 BUILD_TYPE=RELEASE
      compiler: clang
      addons: *addons-clang38-boost155-qt4

script:
  - cd $TRAVIS_BUILD_DIR
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -D CMAKE_C_COMPILER=$C_COMPILER -D CMAKE_CXX_COMPILER=$CXX_COMPILER -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D ma_force_qt_major_version=$QT_MAJOR_VERSION -D ma_coverage_build=$COVERAGE_BUILD ..
  - cmake --build . --config $BUILD_TYPE
  - if [[ "$COVERAGE_BUILD" == "ON" ]]; then
      lcov --directory . --zerocounters;
    fi
  - ctest --build-config $BUILD_TYPE --verbose
  - if [[ "$COVERAGE_BUILD" == "ON" ]]; then
      lcov --directory . --capture --output-file lcov.info;
      lcov --remove lcov.info 'tests/*' '/usr/*' 'boost/*' 'gtest/*' --output-file lcov.info;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
