#
# Copyright (c) 2016 Marat Abrarov (abrarov@gmail.com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

language: cpp
sudo: false

matrix:
  include:
    # GCC 5, Boost 1.55. Qt 4.x
    - env: COMPILER=g++-5 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &gcc5-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-5
            - g++-5
            - libboost1.55-all-dev
            - libqt4-dev
          sources: &package-sources
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - boost-latest
            - ubuntu-sdk-team
    - env: COMPILER=g++-5 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *gcc5-boost155-qt4
    # GCC 4.9, Boost 1.55. Qt 4.x
    - env: COMPILER=g++-4.9 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &gcc49-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.9
            - g++-4.9
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *package-sources
    - env: COMPILER=g++-4.9 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *gcc49-boost155-qt4

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_CXX_COMPILER=$COMPILER -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D ma_force_qt_version=$QT_VERSION ..
  - cmake --build . --config $BUILD_TYPE --clean-first
  - ctest --build-config $BUILD_TYPE --verbose
