#
# Copyright (c) 2016 Marat Abrarov (abrarov@gmail.com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

language: cpp
sudo: required
dist: trusty

env:
  global:
    - secure: "XIrLiwzUWvYOcJRa5c4rtPWEm9tBtjtzH2DqiAhfYZJftDrJkPFJg3YTb2qrNTSVNAXxbkkA56qUX3V3XFh+kU3EYtt4alsrsC7UnLI+axzLRK1ZTGT0AOUVnEKRkMExnLUIJYBnIvwhXLjQnmdYyxAtq2sApsDoGZbUEEhO2+x8s3vGS+/YxoN6lpWm0CHwa/Nv6YqfKhzkQW1GTYEBQSrZPX5j3FL/I/3+caf6uydgM7kxzlmuBjVhnb4f9AGcbDCpJw/mgdKyEuau781xzEz8myiZFyprfjVGHdLjqof2qILrPrbdM1h39NCX+WB7ulrC5lXWWf64OijEI5rpSWAzjxgHUmxDadwrsVjW6c7DXYB99CJ7WhT8S4kbaPsh3zTBzM/fmo3iXxy3s+waFbb4ZjtlGt5s7KOP4USrerHj1c3MHOFuuZDeZiw7h9D+PvILlkbfffnZzr3DTnFmz3Fh1rBLwDSQC0Y/H3o4IO17SBzQStK7vHlFKg8QgM6oiR6TF2B4jSrSHmNLYvuyzcAjwy2cyZs9anyK30SOi7YhRp9pP3rOj94Wbt/NfjwELeJBrNuaumPS4KlKPaI1yvsGTgXekiE8RKq6p2I+HhsZm67hpmSjfPUW4A4eP9tE0v7FqFvJAOtNX/bdWMJ3CH/oSm0g5yr1qLw2qDQrZP8="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

matrix:
  include:
    # GCC 5, Boost 1.55. Qt 5.x
    - env: COMPILER=g++-5 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc5-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-5
            - g++-5
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: &gcc-package-sources
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - boost-latest
        coverity_scan:
          project:
            name: "mabrarov/asio_samples"
          notification_email: abrarov@gmail.com
          build_command_prepend: "cd $TRAVIS_BUILD_DIR && rm -rf build && mkdir build && cd build && cmake -D CMAKE_CXX_COMPILER=$COMPILER -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D ma_force_qt_version=$QT_VERSION .."
          build_command: make
          branch_pattern: coverity_scan
    - env: COMPILER=g++-5 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc5-boost155-qt5
    # GCC 4.9, Boost 1.55. Qt 5.x
    - env: COMPILER=g++-4.9 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc49-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.9
            - g++-4.9
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: *gcc-package-sources
    - env: COMPILER=g++-4.9 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc49-boost155-qt5
    # GCC 4.8, Boost 1.55. Qt 5.x
    - env: COMPILER=g++-4.8 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc48-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.8
            - g++-4.8
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: *gcc-package-sources
    - env: COMPILER=g++-4.8 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc48-boost155-qt5
    # GCC 4.6, Boost 1.55. Qt 5.x
    - env: COMPILER=g++-4.6 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc46-boost155-qt5
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.6
            - g++-4.6
            - libboost1.55-all-dev
            - qtbase5-dev
          sources: *gcc-package-sources
    - env: COMPILER=g++-4.6 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc46-boost155-qt5
# Removed because of LLVM servers (packages) are inaccessible
#    # Clang 3.6, Boost 1.55. Qt 5.x
#    - env: COMPILER=clang++-3.6 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=DEBUG
#      compiler: clang
#      addons: &addons-clang36-boost155-qt5
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.6
#            - libboost1.55-all-dev
#            - qtbase5-dev
#          sources: &llvm36-package-sources
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.6
#            - boost-latest
#    - env: COMPILER=clang++-3.6 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=RELEASE
#      compiler: clang
#      addons: *addons-clang36-boost155-qt5
#    # Clang 3.7, Boost 1.55. Qt 5.x
#    - env: COMPILER=clang++-3.7 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=DEBUG
#      compiler: clang
#      addons: &addons-clang37-boost155-qt5
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.7
#            - libboost1.55-all-dev
#            - qtbase5-dev
#          sources: &llvm37-package-sources
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
#            - boost-latest
#    - env: COMPILER=clang++-3.7 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=RELEASE
#      compiler: clang
#      addons: *addons-clang37-boost155-qt5
#    # Clang 3.8, Boost 1.55. Qt 5.x
#    - env: COMPILER=clang++-3.8 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=DEBUG
#      compiler: clang
#      addons: &addons-clang38-boost155-qt5
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.8
#            - libboost1.55-all-dev
#            - qtbase5-dev
#          sources: &llvm38-package-sources
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.8
#            - boost-latest
#    - env: COMPILER=clang++-3.8 BOOST_VERSION=1.55 QT_VERSION=5 BUILD_TYPE=RELEASE
#      compiler: clang
#      addons: *addons-clang38-boost155-qt5
    # GCC 5, Boost 1.55. Qt 4.x
    - env: COMPILER=g++-5 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc5-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-5
            - g++-5
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *gcc-package-sources
    - env: COMPILER=g++-5 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc5-boost155-qt4
    # GCC 4.9, Boost 1.55. Qt 4.x
    - env: COMPILER=g++-4.9 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc49-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.9
            - g++-4.9
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *gcc-package-sources
    - env: COMPILER=g++-4.9 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc49-boost155-qt4
    # GCC 4.8, Boost 1.55. Qt 4.x
    - env: COMPILER=g++-4.8 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc48-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.8
            - g++-4.8
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *gcc-package-sources
    - env: COMPILER=g++-4.8 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc48-boost155-qt4
    # GCC 4.6, Boost 1.55. Qt 4.x
    - env: COMPILER=g++-4.6 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=DEBUG
      compiler: gcc
      addons: &addons-gcc46-boost155-qt4
        apt:
          packages:
            - cmake
            - cmake-data
            - gcc-4.6
            - g++-4.6
            - libboost1.55-all-dev
            - libqt4-dev
          sources: *gcc-package-sources
    - env: COMPILER=g++-4.6 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=RELEASE
      compiler: gcc
      addons: *addons-gcc46-boost155-qt4
# Removed because of LLVM servers (packages) are inaccessible
#    # Clang 3.6, Boost 1.55. Qt 4.x
#    - env: COMPILER=clang++-3.6 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=DEBUG
#      compiler: clang
#      addons: &addons-clang36-boost155-qt4
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.6
#            - libboost1.55-all-dev
#            - libqt4-dev
#          sources: *llvm36-package-sources
#    - env: COMPILER=clang++-3.6 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=RELEASE
#      compiler: clang
#      addons: *addons-clang36-boost155-qt4
#    # Clang 3.7, Boost 1.55. Qt 4.x
#    - env: COMPILER=clang++-3.7 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=DEBUG
#      compiler: clang
#      addons: &addons-clang37-boost155-qt4
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.7
#            - libboost1.55-all-dev
#            - libqt4-dev
#          sources: *llvm37-package-sources
#    - env: COMPILER=clang++-3.7 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=RELEASE
#      compiler: clang
#      addons: *addons-clang37-boost155-qt4
#    # Clang 3.8, Boost 1.55. Qt 4.x
#    - env: COMPILER=clang++-3.8 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=DEBUG
#      compiler: clang
#      addons: &addons-clang38-boost155-qt4
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.8
#            - libboost1.55-all-dev
#            - libqt4-dev
#          sources: *llvm38-package-sources
#    - env: COMPILER=clang++-3.8 BOOST_VERSION=1.55 QT_VERSION=4 BUILD_TYPE=RELEASE
#      compiler: clang
#      addons: *addons-clang38-boost155-qt4

script:
  - cd $TRAVIS_BUILD_DIR
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -D CMAKE_CXX_COMPILER=$COMPILER -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D ma_force_qt_version=$QT_VERSION ..
  - cmake --build . --config $BUILD_TYPE
  - ctest --build-config $BUILD_TYPE --verbose
